title: VSN Sai Krishna Mohan Kocherlakota
logo: /img/headshot.png
description: As an accomplished Data Scientist and Machine Learning Engineer with proven proficiency in R, Python, Excel (Basic and advanced), 
and Power BI for data analysis and visualization, I bring to the table a distinctive combination of technical expertise and leadership skills 
that consistently delivers successful project outcomes. Additionally, my experience includes a solid foundation in NLP (Natural Language Processing), Gen AI, 
and other machine learning techniques, further enriching my capabilities.
show_downloads: true
theme: Jekyll-theme-minimal
